//tealium universal tag - utag.217 ut4.0.202407011441, Copyright 2024 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.loader_cb=function(){u.initialized=true;var customer_status='';var customer_reg_status='';var customer_email='unknown';var isChatBannnerClicked=false;if(typeof digitalData.user.attributes.customer_status!="undefined"&&digitalData.user.attributes.customer_status!=""){customer_status=digitalData.user.attributes.customer_status;if(customer_status==="anonymous"){customer_status='not logged in'}}
if(typeof digitalData['user']["attributes"]["customer_reg_status"]!="undefined"&&digitalData['user']["attributes"]["customer_reg_status"]!=""){customer_reg_status=digitalData['user']["attributes"]["customer_reg_status"];if(customer_reg_status==="new"){customer_reg_status='not autheticated'}}
if(typeof digitalData['user']["profile"]["profileInfo"]['profileEmail']!="undefined"&&digitalData['user']["profile"]["profileInfo"]['profileEmail']!=""){customer_email=digitalData['user']["profile"]["profileInfo"]['profileEmail'];}
if(typeof digitalData['page']["attributes"]["page_url"]!="undefined"&&digitalData['page']["attributes"]["page_url"]!=""){isChatBannerClicked=digitalData['page']["attributes"]["page_url"].includes("t/holiday?send_message=christmas%20gifting");}
$aivo.ready(function(){$aivo.user.set("customer_status",customer_status);$aivo.user.set("customer_reg_status",customer_reg_status);$aivo.user.set("customer_email",customer_email);if(!isChatBannerClicked){$aivo.chat.minimize(true);}});};var scriptPath="//cdn.agentbot.net/core/ec0633155e0d2eb58138ea776921e7f0.js";if(!u.initialized){u.loader({"type":"script","src":scriptPath,"cb":u.loader_cb,"loc":"script","id":'utag_217',"charset":"UTF-8"});}else{u.loader_cb();}
}};utag.o[loader].loader.LOAD(id);})("217","bbw.new");}catch(error){utag.DB(error);}
