//tealium universal tag - utag.236 ut4.0.202407011441, Copyright 2024 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<41){u.loader=function(o,a,b,c,l,m){utag.DB(o);a=document;if(o.type=="iframe"){m=a.getElementById(o.id);if(m&&m.tagName=="IFRAME"){b=m;}else{b=a.createElement("iframe");}o.attrs=o.attrs||{};utag.ut.merge(o.attrs,{"height":"1","width":"1","style":"display:none"},0);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";}if(o.id){b.id=o.id;}for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=="complete"||this.readyState=="loaded"){this.onreadystatechange=null;o.cb();}};}}if(o.type!="img"&&!m){l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1};u.map={};u.extend=[function(a,b){try{if((typeof b['loyalty_signup_event']!='undefined'&&b['loyalty_signup_event'].toString().toLowerCase().indexOf('true'.toLowerCase())>-1&&typeof b['transaction_id']!='undefined'&&typeof b['order_id']!='undefined')){b['transaction_id']='';b['order_id']='';b['_corder']=''}}catch(e){utag.DB(e);}},function(a,b){try{if(1){b.product_category=utag.data.product_category.replace(/\s/g,"%20").split("|");}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:236");utag.DB(b);var c,d,e,f,i;u.data={"qsp_delim":"&","kvp_delim":"=","dynamic_base_url":"//t.pepperjamnetwork.com/track?","container_base_url":"	//container.pepperjam.com/##cid##.js","cid":"357974502","pid":"4333","integration":"DYNAMIC","product_id":[],"product_category":[],"product_quantity":[],"product_unit_price":[]};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:236:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
utag.DB("send:236:MAPPINGS");utag.DB(u.data);u.data.order_id=u.data.order_id||b._corder||"";u.data.order_coupon_code=u.data.order_coupon_code||b._cpromo||"";if(u.data.product_id.length===0&&b._cprod!==undefined){u.data.product_id=b._cprod.slice(0);}
if(u.data.product_category.length===0&&b._ccat!==undefined){u.data.product_category=b._ccat.slice(0);}
if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(u.data.product_unit_price.length===0&&b._cprice!==undefined){u.data.product_unit_price=b._cprice.slice(0);}
if(!u.data.cid){utag.DB(u.id+": Tag not fired: Required attribute 'Container Tag's ID' not populated");return;}
u.data.container_base_url=u.data.container_base_url.replace("##cid##",u.data.cid);if(u.data.pid&&u.data.order_id!==""){var query_param_click_id=b["qp.clid"];var cookie_click_ids=b["cp.utag_main_pepperjam_click_ids"]?b["cp.utag_main_pepperjam_click_ids"].split(","):[];if(query_param_click_id){var index_in_cookie=cookie_click_ids.indexOf(query_param_click_id);if(index_in_cookie!==-1){cookie_click_ids.splice(index_in_cookie,1);}
cookie_click_ids.push(query_param_click_id);utag.loader.SC("utag_main",{"pepperjam_click_ids":cookie_click_ids.join(",")});}
c.push("INT"+u.data.kvp_delim+u.data.integration);c.push("PROGRAM_ID"+u.data.kvp_delim+u.data.pid);c.push("ORDER_ID"+u.data.kvp_delim+u.data.order_id);for(i=0;i<u.data.product_id.length;i++){if(u.data.product_id[i]!=""){c.push("ITEM_ID"+(i+1)+u.data.kvp_delim+u.data.product_id[i]);c.push("QUANTITY"+(i+1)+u.data.kvp_delim+(u.data.product_quantity[i]?u.data.product_quantity[i]:"1"));c.push("ITEM_PRICE"+(i+1)+u.data.kvp_delim+(u.data.product_unit_price[i]?u.data.product_unit_price[i]:"0"));if(u.data.product_category[i]!==undefined){c.push("CATEGORY"+(i+1)+u.data.kvp_delim+u.data.product_category[i]);}}}
if(u.data.order_coupon_code){c.push("COUPON"+u.data.kvp_delim+u.data.order_coupon_code);}
if(u.data.new_to_file){c.push("NEW_TO_FILE"+u.data.kvp_delim+u.data.new_to_file);}
if(cookie_click_ids.length>0){c.push("CLICK_ID"+u.data.kvp_delim+cookie_click_ids.join(","));}
u.loader({"type":"iframe","src":u.data.dynamic_base_url+c.join(u.data.qsp_delim),"loc":"body","id":"utag_236","attrs":{}});}else{utag.DB(u.id+": Dynamic pixel not fired: Required attribute 'Program ID' and/or 'Order ID' not populated");}
u.loader({"type":"script","src":u.data.container_base_url,"loc":"body","id":"utag_236","attrs":{}});utag.DB("send:236:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("236","bbw.new"));}catch(error){utag.DB(error);}
